### ISSUE TITLE
Consider adding a stackblitz url

### ISSUE THREAD

**Issue by rajsite** [tomsoftware/vi-explorer.ts#1]
Was able to run the project completely in-browser using stackblitz: https://stackblitz.com/github/tomsoftware/vi-explorer.ts

Could consider adding a link for that to the README to make it easier to quickly experiment with the project. I had to manually start the server in the stackblitz console by running `npm run serve` but if you renamed the command `start` it would start automatically.

**Comment by tomsoftware** [comment]
You are too fast :-D 

I already setup a "demo"-page but did not add it to the readme because of a bug -> i fixed this and add a link to this demo-page.

Thanks for the stackblitz hint!
`npm run serve` is the default command to debug *vue* apps so I will not remove this but I added the `start` command so stackblitz https://stackblitz.com/github/tomsoftware/vi-explorer.ts also works fine now. cool and thanks!

FYI: This project is in a early state... next step is to show all objects of the Block-Diagram as tree-view and then try to render this a svg... I'm lucky for every feedback!

**Comment by rajsite** [comment]
Very cool! Always excited to see web projects with LabVIEW :)
